### ISSUE TITLE
Access to pre-DLC version

### ISSUE THREAD

**Issue by Xiom834** [RoboPhred/oni-duplicity#105]
Can we get access to the 15.3 version please ? or a how-to guide to using the source code.
I tried copying the files in a website on my win10 machine but it says it needs a module of some sort, i have no idea what it wants :(
I also tried opening the source code folder in visual studio and RUNning it without debugging but I get a 404.3 error too.

**Comment by vivek201** [comment]
I updated `@types/i18next` to `^13.0.0` and `i18next` to `^17.0.0`. Then I deleted `package-lock.json` before running `npm install`.
