### ISSUE TITLE
Error loading save

### ISSUE THREAD

**Issue by HolCrafter** [RoboPhred/oni-duplicity#112]
I received this error while trying to modify my save form today's update the suspicious seed update.
Error while processing content: Save version "7.23" is not compatible with this parser. Expected version "7.17,22".

I was wondering when the editor will be updated to support the new file  formate

**Comment by RoboPhred** [comment]
Can you provide me with a save file from this version so I can check to see if any parser changes are needed?  I have been out of the game and do not have the DLC to test with.

**Comment by HolCrafter** [comment]
[Acropolis.zip](https://github.com/RoboPhred/oni-duplicity/files/6475172/Acropolis.zip)

**Comment by supermario228282** [comment]
will there be an update for the new version of the game

**Comment by Paretor** [comment]
looking forward for an update!

**Comment by RoboPhred** [comment]
Thanks.  I didn't see any obvious breaking changes in this version so I bumped up the version lock.  Please try out the editor with this new version and let me know if anything is broken.

**Comment by Paretor** [comment]
i did notice some new types of geysers arent appearing in the editor, for example brine and aluminum volcano/geyser
can look into that.
i didnt check it properly but maybe some traits are missing.

thanks again for your work and response!

**Comment by monkewt** [comment]
Save version "7.22" is not compatible with this parser. Expected version "7.17,23". 
sorry but i can't load my save for some reason :(
