### ISSUE TITLE
Error loading save

### ISSUE THREAD

**Issue by Bakiaa** [RoboPhred/oni-duplicity#116]
I've received an error when trying to load my save:
"Error while processing content: Save version "7.25" is not compatible with this parser. Expected version "7.17,23""

**Comment by wildwinds86** [comment]
Also getting the same issue. Please update :)

**Comment by RoboPhred** [comment]
Updated to allow this save version to load, as well as to provide a means of bypassing this check in the future.

Please test out the new editor with your saves to make sure nothing else has changes.  I was not able to test anything but a fresh new save, so its possible you might run into issues on a more fully developed save.

Leaving this issue open for now until I am sure that there are no game / save breaking bugs.

**Comment by glenmack** [comment]
@RoboPhred Thank you for getting to this quickly, this utility vastly improves my enjoyment of the game, I hope you continue to maintain it for a long time to come.

**Comment by wolkenschieber** [comment]
I'm getting: Error while processing content: Save version "7.27" is not compatible with this parser. Expected version "7.25".

Looks like Duplicity and the DLC both made one step ahead :)

**Comment by ZyborgRSA** [comment]
I'm getting the following error when trying to load a save file: "Error while processing content: Unexpected token P in JSON at position 0"
