### ISSUE TITLE
Fast Friends Update: Duplicant Tab Broke

### ISSUE THREAD

**Issue by Apprisco** [RoboPhred/oni-duplicity#127]
As said in title, the most recent ONI Update the duplicants tab of Duplicity, if it's still being maintained.

**Comment by StriateCash** [comment]
I have found this issue as well, screen just goes white and I can't do anything.

**Comment by DraugrBreath** [comment]
Same. Works at start of the game but after you get your 4th duplicant it stops working.

**Comment by Devlah** [comment]
Build: U42-510972-5
After acquiring 4th Duplicant, the duplicant tab has white screen and loses functionality on load.

**Comment by Sordid89** [comment]
The problem is the new Duplicants, i can use it just fine but when i print one of the new duplicants it just goes white.

**Comment by Dobratr** [comment]
I can't make it work from the start. Could anyone send me a new savegame from Terra that can be editable?

**Comment by RoboPhred** [comment]
If someone could get me a link to a copy of a save file that has the issue, I could take a look at it.

**Comment by DraugrBreath** [comment]
https://drive.google.com/file/d/1wr4enAkfkNRhgNHoLJLIPIV6oSi4Tri0/view?usp=sharing

**Comment by Dobratr** [comment]
Sorry for the time zone delay.

Here is the link to the save file that I can't edit the duplicants stats.
The Outrageous Gang.zip<https://we.tl/t-06BeOEQkhe>
I have created the world is a **cloud** save.

By the way, I don't have the **Spaceout DLC**. Only the main game with **Friends update**.

After I reported the issue, I created a new world as a **local** save and I could successfully edit it.
Here is the link.
Lone Pit - START.sav<https://we.tl/t-V1St0EQD8y>

Thanks for your help.

**Comment by RoboPhred** [comment]
Both of these saves are crashing because they have duplicants with different hair types than expected.  I can patch out the issue for now and let the duplicants appear bald, but ultimately I need to extract the new art assets.  Unfortunately, it's been a long time since I last did that and I don't really remember the process.

**Comment by RoboPhred** [comment]
I pushed an update that fixes the crash.  The duplicants in question will not have any hair in the editor, but as long as you do not try to change their hair they should maintain their real hair through editing.
