### ISSUE TITLE
Question about Support

### ISSUE THREAD

**Issue by OriginalFoamy** [RoboPhred/oni-duplicity#139]
Hey, I wanted to thank you for all the work you've put into this so far. I've been using Duplicity to play ONI since you first developed it, and for me it is an essential piece to the game.

Because life often gets in the way, I understand that unpaid projects like this are often a low priority for the developer. My only question is whether or not, at some point, you intend to update it or not? Or perhaps it's already being worked on?

I've been checking changelog every day since the newest patch came out just to see if you had updated it. Whether you will continue to update it or not is quite obviously your choice, but I simply would like to know if I should continue to check, or whether I should give up any hope that an update is coming.

Thanks for everything!

**Comment by RoboPhred** [comment]
I haven't played this game in years, and this project really isn't in my sights anymore.  I will take a look and see if the last few updates are something I can sneak in though.
