### ISSUE TITLE
Missing arm color in appearance menu

### ISSUE THREAD

**Issue by hieuv** [RoboPhred/oni-duplicity#2]
I believe there should be one more appearance option for arm color.

**Comment by RoboPhred** [comment]
I don't recall seeing this in the appearance data.

The current appearance properties I recognize are shared between the [Accessorizer](https://github.com/RoboPhred/oni-save-parser/blob/master/src/versions/7_3/behaviors/accessorizer.ts) behavior and the [MinionIdentity](https://github.com/RoboPhred/oni-save-parser/blob/master/src/versions/7_3/behaviors/minion-identity.ts) behavior.

I will stick it on my todo list to take another look.
