### ISSUE TITLE
Weasels were probably involved

### ISSUE THREAD

**Issue by rajdakin** [RoboPhred/oni-duplicity#23]
Hello.

When I tried to load a save file, I got an error message:
> I don't know how you got here...
> But weasels were probably involved.
> No idea what this page is supposed to be, sorry.
> Try choosing something else to edit.

It keeps repeating it, no matter the save file (or it simply ignore the save file, probably because the save was for another ONI version...).

Due to that, I cannot use your editor.

By the way, I'm on Linux (Linux Mint 18.3) if this helps.

**Comment by RoboPhred** [comment]
Sorry about that.  This is a known ui bug. Once you see that screen, click on of the menu items on the left and you should be able to edit things.

This probably won't be fixed until the site is totally replaced by the rewrite in the works.  If you want to follow it's progress, I periodically release alpha builds on https://robophred.github.io/oni-duplicity/vnext/

**Comment by rajdakin** [comment]
Right, thanks!
You should tell this on the main screen.
(By the way, you could also tell that on Linux, the saves are in `~/.config/unity3d/Klei/Oxygen Not Included/save_files`)
