### ISSUE TITLE
not able to load my previous CU and new EU save file 

### ISSUE THREAD

**Issue by Nuiyuki** [RoboPhred/oni-duplicity#24]
When I try to load my save file it won't work and an error message pops up :/
Tried with my previous save file from the cosmic update and a new save file from the expressive update.

Error message:

![screenshot_28_07_2018](https://user-images.githubusercontent.com/26405647/43355861-d6bf9782-9264-11e8-8787-9e9ebd3421d7.jpg)

or am I doing something wrong?

**Comment by RoboPhred** [comment]
Do you get this same error from both saves?  Did your new EU save file get created after the public release, or was it saved during the alpha?

Does it work if you force a "new save" and try to load that one?

My guess would be that older saves are not getting updated to the newer format.  I may have to allow both CU and EU save versions.

Luckally, as far as I can tell, the part of the save format that changed was never used in the CU, so I should be able to just tell the editor to allow them without having to make it handle each version differently

**Comment by RoboPhred** [comment]
Update: I just loaded a CU save into the game, re-saved it, then opened it in the editor successfully.  The game should be upgrading your save files, just be sure to make it save them manually before trying to edit them.

**Comment by Nuiyuki** [comment]
okay I saved the old save file manually and it works now, seems to be bugged with auto save o:
thanks for the fast response :D

**Comment by Nuiyuki** [comment]
okay I saved the old save file manually and it works now, seems to be bugged with auto save o:
thanks for the fast response :D

**Comment by sand-castle** [comment]
i have the same problem here, i do try use the old save (cosmic) it can't be work, then i try use the newer (expressive) doesn't work either. it says same like the picture

**Comment by Nuiyuki** [comment]
you need the newest update (IIRC version 279738)
