### ISSUE TITLE
Offline Editor? {Feature Request}

### ISSUE THREAD

**Issue by 5HT2** [RoboPhred/oni-duplicity#25]
Is there a way to wrap all the components in a js file [in a html file] so this works offline?

**Comment by RoboPhred** [comment]
I am not sure about a downloadable html-form editor.  Chrome (and presumably other browsers) has some security features that kick in when the file is hosted locally, and I think that it will stop the site from loading or saving files.

However, I could set up a [service worker](https://caniuse.com/#feat=serviceworkers), which could provide the option for the site to be downloaded and ran from the browser in an offline mode.  This would still require going to the site directly and opting in, but it should allow it to be used when an internet connection is not available.

For a direct download, I could try wrapping it in [electron](https://github.com/electron/electron), but I have not played with that for some time and it may be a larger project.

I suspect I will go the service worker route, when I get the time to handle this.
