### ISSUE TITLE
Mirror sites

### ISSUE THREAD

**Issue by zsnmwy** [RoboPhred/oni-duplicity#26]
First,I have to say your website is very useful.

I recommend to my friends.

Unfortunately,we always get the error code when browser the web site in China.

Because the server is far away from my location. China ----- USA

I want to make a mirror site in China.

Can you allow me to do this?

Thanks.

**Comment by RoboPhred** [comment]
Certainly!  The code is licensed under the MIT license, so you can make a copy and modify it however you like, as long as you include the original LICENSE file somewhere the user can see it from the site.
You can find more info on the license at https://tldrlegal.com/license/mit-license

You can find pre-built copies of the site under the gh-pages branch, but these are built intending to be hosted at the subpath "/oni-duplicity" and may break if hosted on a different path.  If your path is different, you should recompile the site with the public path you want.

You can do this by changing the [public path](https://github.com/RoboPhred/oni-duplicity/blob/5c47e00014725c005d6ee9e6d1e52debb54635b4/config/paths.js#L9) configuration variable, and running `npm run build`.  The new files will be compiled into the `/dist` folder.

Keep in mind that right now I use a [custom font](https://github.com/RoboPhred/oni-duplicity/blob/5c47e00014725c005d6ee9e6d1e52debb54635b4/src/index.ejs#L8) provided by google.  It's on my list to compile this into the website as well, but until then you may want to make sure that url is not also slowing down the hosting of the site.

Other than that font, nothing else is hosted externally.


I am still tracking your translation feature request over at #4 as well.  Once I handle the last few bugs being reported, I will try to make getting i18n a priority.
