### ISSUE TITLE
Map Traits to their In-game names

### ISSUE THREAD

**Issue by hieuv** [RoboPhred/oni-duplicity#3]
Traits are currently listed with (what I presumed to be) their development name. It would be more helpful to list them with their in-game display name.

**Comment by RoboPhred** [comment]
They are displayed using the same name they are serialized with in the save file.  If someone wants to help out and make a list of the internal names to in-game names, that would be a great help!

**Comment by Lockhead** [comment]
Hope this helps...

file|game
-|-
IrritableBowel|Irritable Bowel
Aggressive|Destructive
StrongArm|Buff
Twinkletoes|Twinkletoes
UglyCrier|Ugly Crier
CantResearch|Yokel
BedsideManner|Caregiver
Stinky|Stinkiness
Ellie|Fastidious
Joshua|Cheery Disposition
Liam|Germaphobe
CantBuild|Unconstructive
CantCook|Gastrophobia
CantDig|Trypophobia
Hemophobia|Squeamish
MedicalAid|??? not visible ingame ???
ScaredyCat|Pacifist
MouthBreather|Mouth Breather
CalorieBurner|Bottomless Stomach
SmallBladder|Small Bladder
Anemic|Anemic
SlowLearner|Slow Learner
NoodleArms|Noodle Arms
InteriorDecorator|Interior Decorator
Regeneration|Regenerative
DeeperDiversLungs|Deeper Diver's Lungs
SunnyDisposition|Sunny Disposition
RockCrusher|Rock Crusher
Uncultured|Uncultured
WeakImmuneSystem|Biohazardous
Flatulence|Flatulent
Snorer|Loud Sleeper
Narcolepsy|Narcoleptic
Greasemonkey|Grease Monkey
MoleHands|Mole Hands
FastLearner|Quick Learner
DiversLung|Diver's Lung
IronGut|Iron Gut
StrongImmuneSystem|Germ Resistant
Caring|??? not visible ingame ???
BingeEater|Binge Eater
StressVomiter|Vomiter
EarlyBird|Early Bird
NightOwl|Night Owl
Claustrophobic|??? not visible ingame ???
PrefersWarmer|Skinny
PrefersColder|Pudgy
SensitiveFeet|Delicate Feetsies
Fashionable|Fashionista
Climacophobic|Vertigo Prone
SolitarySleeper|Solitary Sleeper
Workaholic|Workaholic

**Comment by RoboPhred** [comment]
Thanks for putting these together!

This issue is dependent on #4, as I intend to use the translation system to turn the internal names into the names the user will see.  This makes things easier for me, and the names will change based on the game language anyway.

**Comment by RoboPhred** [comment]
This is now in the master branch and live on /vnext
