### ISSUE TITLE
Save version error

### ISSUE THREAD

**Issue by kaisuke143** [RoboPhred/oni-duplicity#31]
Error: Save version "7.4" is not compatible with this parser. Expected version "7.5". at Object.n.parseSaveGame (https://robophred.github.io/oni-duplicity/adfd6c607b205722fbfd.worker.js:1:651599) at n.parseSaveGame.next (<anonymous>) at Object.a [as parse] (https://robophred.github.io/oni-duplicity/adfd6c607b205722fbfd.worker.js:1:639470) at Object.n.parseSaveGame (https://robophred.github.io/oni-duplicity/adfd6c607b205722fbfd.worker.js:1:40033) at https://robophred.github.io/oni-duplicity/adfd6c607b205722fbfd.worker.js:1:39314 at https://robophred.github.io/oni-duplicity/adfd6c607b205722fbfd.worker.js:1:39416

It says this,but i already have the expressive update. What do i do?

**Comment by RoboPhred** [comment]
You need to be running the latest stable version for the editor to work.  You are probably still on the alpha branch.
