### ISSUE TITLE
Need method to set attributes to all duplicants

### ISSUE THREAD

**Issue by ArunPrasath-M** [RoboPhred/oni-duplicity#33]
Just need a method to increase stats for all dupes in one click and need a button to give trait to all dupes in one click

**Comment by RoboPhred** [comment]
Related to #36.  Probably need to solve it with a macro / bulk edit mode.

**Comment by metroid112** [comment]
If you could do this it would be great

**Comment by RoboPhred** [comment]
The master branch (and /vnext) now supports a form of this.  If you set all of the attributes you want on one duplicant, you can then copy those attributes and paste them on the others.  The copy menu is in the 3-dots dropdown menu icon on the duplicant list page.
