### ISSUE TITLE
Can't change attitudes and skills of certain dupes

### ISSUE THREAD

**Issue by lubenja** [RoboPhred/oni-duplicity#34]
Certain skills and attitudes can't be lowered to 0.

Which ones depend on the dupes. It looks like you can't lower the  skills below 1 and can't delete attitudes the respective dupe has been spawned with.

For some dupes the changed skills won't be saved at all. (try with Meister Eder e.g. in the save game) 
Sometimes if only impossible to change certain skills while with other the changes will be saved (same dupe). 
Save Game: https://forums.kleientertainment.com/forums/topic/89789-save-file-editor/?do=findComment&comment=1074081

**Comment by RoboPhred** [comment]
Sigh, this will be the third time I fixed that off-by-one bug in the numeric input.  Thanks.

I cant reproduce the issue for Meister Eder, so I think that might have fallen under a previous fix in the general area.
