### ISSUE TITLE
Missing Trait

### ISSUE THREAD

**Issue by redthefed** [RoboPhred/oni-duplicity#35]
If I'm not mistaken the trait Foodie is missing from the editor.

**Comment by unmog** [comment]
I was going to say the same thing, Foodie, as well as simple tastes. Unless its the same trait with a different name.

**Comment by RoboPhred** [comment]
Fixed in https://github.com/RoboPhred/oni-duplicity/commit/2312cbfefb327e09cb69e175a0fbb3d0d8396ee4
