### ISSUE TITLE
Assign traits to all duplicants at once #featureRequest

### ISSUE THREAD

**Issue by jessehattabaugh** [RoboPhred/oni-duplicity#36]
Would be nice to have when I'm trying to make sure none of my dupes are Destructive. Currently have to go into each Dupe and check the boxes.

**Comment by RoboPhred** [comment]
~~Duplicate of https://github.com/RoboPhred/oni-duplicity/issues/36~~

Scratch that, linked issue was attributes.

**Comment by RoboPhred** [comment]
This is implemented by being able to copy and paste attributes between duplicants
