### ISSUE TITLE
"Stamina" misspelled

### ISSUE THREAD

**Issue by jessehattabaugh** [RoboPhred/oni-duplicity#37]
https://github.com/RoboPhred/oni-duplicity/blob/7165b60d352e921cb83203950f3c3a4bdb9b1e3f/src/pages/SaveEditor/components/editors/game-objects/MinionEditor/components/MinionHealthTab/MinionHealthTab.tsx#L83

**Comment by RoboPhred** [comment]
Whoops, thanks!
