### ISSUE TITLE
Save version 7.6

### ISSUE THREAD

**Issue by clayton69** [RoboPhred/oni-duplicity#38]
When will save version 7.6 be available for editing? And thank you for all the hard work!!!

**Comment by RoboPhred** [comment]
I just reviewed it and wasn't able to find any obvious incompatibilities.  It loads a very basic save just fine.  I've updated the header check to allow 7.6, but I have not given it a comprehensive test.

Go ahead and give it a try, let me know if you find a case where it fails.

**Comment by clayton69** [comment]
no problems
