### ISSUE TITLE
TraitsSkillsAptitudes

### ISSUE THREAD

**Issue by Sijko** [RoboPhred/oni-duplicity#39]
1. Traits

- color red and green the good and bad
- make a save-able set of user preferred traits with a button to apply to all
- popup info or in a column
- a button apply current to all

2. Skills
Level  -> button for raise all for this dupe by "input" number
           -> button for raise all for this dupe up to the "input" number
           -> button for raise all for all dupes by "input" number
           -> button for raise all for all dupes  up to the "input" number

3. Aptitudes -> button for raise all for this dupe by "input" number
                    -> button for raise all for this dupe up to the "input" number
                    -> button for raise all for all dupes by "input" number
                    -> button for raise all for all dupes  up to the "input" number

**Comment by RoboPhred** [comment]
Traits can now be copied from one duplicant to another, which should solve for the traits list request.  As for bulk changing of skills or aptitudes, I am going to leave that out as its not particularly hard to change individual values.  If you are trying to max all stats, you just have to change one duplicant and copy it to the rest.
