### ISSUE TITLE
Provide for translations using i18n

### ISSUE THREAD

**Issue by zsnmwy** [RoboPhred/oni-duplicity#4]
I want to translate the web site to my local language.

**Comment by RoboPhred** [comment]
Sounds good to me.  If no one else gets to it, I will add this in on my next pass over the project.  I will need to do more research into how to use this.

For anyone who wants to contribute, [react-i18n](https://github.com/i18next/react-i18next) looks like the best method to go about this.

**Comment by RoboPhred** [comment]
I have started making progress on this.  The core i18next framework is in, and I have started adding some text to it.

Still open for assistance here, if anyone wants to scrub through and find text to translate.

**Comment by zsnmwy** [comment]
Nice!!!  
I want to find text files to translate.  
What should I do?  
Can you give me a detail guide?  
Thanks.

**Comment by RoboPhred** [comment]
You will need to be under the `develop` branch, where you can find the translation folder under [src/i18n/translations](https://github.com/RoboPhred/oni-duplicity/tree/develop/src/i18n/translations).

Right now, the only thing there is english, under the 'en' code.  As I find the time, I will be moving the text of the app into here.

Find the language code you want to use from [here](http://www.i18nguy.com/unicode/language-identifiers.html).  You only need the first half before the dash, so `en-us` becomes `en`.  Make a folder named after your code, and copy the .json files from the en folder over.  Right now, there is only a `common.json` file, but I will be making a `game-data.json` folder when I start to support translating the names of game objects.

Not much text is supported yet aside from the basic load / save / help text; I still need to go through and add the translation mechanism to the rest of the site.

When I get around to enabling the translation of game objects, I hope to make the keys the same as the ones used in oni translation files to make it easier.

**Comment by RoboPhred** [comment]
Chinese language accepted into dev.
Currently, this is accessed by adding `?lng=zh` to the end of the url.

I need to add a settings menu with language selection.  Unfortunately, I cannot auto-detect the language as it seems github's gh-pages does not have a mechanism for handling the `Accept-Language` header.

**Comment by zsnmwy** [comment]
How about use this [js](https://github.com/zsnmwy/ONI-geyser-calculator/blob/master/Script/i18n.js) to solve this problem？

I'm not good at web dev....

But it works on [onical](https://onical.ga).

**Comment by RoboPhred** [comment]
I got this in with a very basic language selection menu on the top right of the app.  Going forward, I will try to get a better solution for that.

Next step will be to get translation support in for the save-specific data, which will be an ongoing process.  I am going to close this issue and open up new ones to track the other areas as I get to them.
