### ISSUE TITLE
Appearance preview

### ISSUE THREAD

**Issue by AgainPsychoX** [RoboPhred/oni-duplicity#40]
I would like to preview appearance of duplicant I build.

The assets for preview could be exported with [Unity Assets Bundle Extractor tool](https://7daystodie.com/forums/showthread.php?22675-Unity-Assets-Bundle-Extractor) (tested 2.2, works fine to export PNG).

Here some exported textures with duplicant bodies elements, that could be used for the preview: https://imgur.com/a/4kClvD3 
I added also some useful screens using the editor to analyse (001, 002 etc.)

How about that?

**Comment by RoboPhred** [comment]
Added in V3
