### ISSUE TITLE
Can't Edit Duplicant Traits

### ISSUE THREAD

**Issue by ApplesOfEpicness** [RoboPhred/oni-duplicity#41]
Clicking on any duplicant and trying to edit them will cause the browser to go white and crash. This doesn't happen in new worlds I generate so i suspect its because my world is from an older version. Worth of shot to see if I can fix it though.

[Core.zip](https://github.com/RoboPhred/oni-duplicity/files/2394193/Core.zip)

**Comment by RoboPhred** [comment]
This is really strange... All of the duplicants have an null entry in their accessory list.  I can't think why or how this could happen, but the editor can handle this by ignoring the bad data.
