### ISSUE TITLE
language problem

### ISSUE THREAD

**Issue by 2625529702** [RoboPhred/oni-duplicity#44]
Also, can you translate the text compiled in the editor into Chinese, we like the editor you wrote.

**Comment by RoboPhred** [comment]
I am open to translations, but I do not speak Chinese and I do not trust google translate to do the job.

Can you help translate the app?  All you need to do is translate the values in the two json files located at https://github.com/RoboPhred/oni-duplicity/tree/master/src/translations/en and include them in the src/translations/zh folder.  If you can get me the translations, I will quickly get them into the application.

**Comment by elumspe** [comment]
I'm working on the first draft of Chinese translation. It should be done soon.

**Comment by RoboPhred** [comment]
Thanks for the MR!  I added a selector to the settings page to change the language.
