### ISSUE TITLE
No load button in new version

### ISSUE THREAD

**Issue by ghost** [RoboPhred/oni-duplicity#49]
Please add a load button next to the save, like the previous version used to.

In the old version you could load as many times as needed - if you loaded the wrong file, or realised you missed a change.

New version allows ONE load from the initial start page. Then you need to reconnect to the internet and reload the app to load again.

My game machine isn't normally online, so this is a major annoyance.

Thanks

**Comment by RoboPhred** [comment]
Added one in, sorry about the oversight.
