### ISSUE TITLE
Mouths don't change?

### ISSUE THREAD

**Issue by Courtflash** [RoboPhred/oni-duplicity#5]
The mouths of my Dupes won't change no matter what I set them to.

**Comment by RoboPhred** [comment]
If you re-load a save in the editor after changing it, is your mouth selection still there?  Or does it reset to the old value?

**Comment by Courtflash** [comment]
OK, so I thought there were different mouth shapes or something (like something different from the constant frown they have), and the mouth option is actually just the skin colour of their cheeks. So it has to have the same number as the "headshape" option.
