### ISSUE TITLE
Cannot save or export with Chrome

### ISSUE THREAD

**Issue by ItGacky** [RoboPhred/oni-duplicity#51]
Downloading won't start on save or export, though "Modified" notification disappears.
No error message is found in the browser's console.

Microsoft Edge works as expected.

**Comment by RoboPhred** [comment]
I've been developing this with Chrome.  I haven't been able to reproduce this.  Do you have an example save file that causes it?

**Comment by ItGacky** [comment]
I found my popup blocker (https://poperblocker.com/) prevents downloads.
Sorry for bothering you.
