### ISSUE TITLE
QoL 3 proper saves are not saving/downloading properly

### ISSUE THREAD

**Issue by Havaren** [RoboPhred/oni-duplicity#52]
using a main branch QoL 3 save throws an error when trying to save the file.

Error while processing content: l.toUnsigned is not a function

this error does not happen with beta branch QoL 3 saves.

**Comment by Havaren** [comment]
- update - seems to have to do with having mods installed. any mod installed via the steam workshop seems to cause the issue.

**Comment by RoboPhred** [comment]
Thanks, knowing this is related to mods is helpful.  I have gotten multiple reports of this, but so far the example saves provided don't seem to reproduce the issue for me.

I will look into how the game is saving the mods list.  I probably need to improve the error messages as well; it would be helpful to report the area of the file that was being parsed at the time of the crash.

**Comment by RoboPhred** [comment]
This is fixed.  Issue was the web code was stripping out the mod version field.
