### ISSUE TITLE
7.6 version support

### ISSUE THREAD

**Issue by gusarov** [RoboPhred/oni-duplicity#54]
Hi, I still playing 7.6 version, going to launch all space missions before performing upgrade... Just realized that online version is now broken.
> Save version "7.6" is not compatible with this parser. Expected version "7.8".

Can you please support multiple versions of a save file?

**Comment by RoboPhred** [comment]
I want to stick to the mainline branch version as much as possible.  I don't really have the ability to go back to old versions to test the editor, so I can't support it directly.

You can find a compatible version in the github tag list and run it yourself though, if a previous version works for you.
