### ISSUE TITLE
Arm color is not changing with body color

### ISSUE THREAD

**Issue by BeatByGirl** [RoboPhred/oni-duplicity#55]
I know the previous version of the editor had fields to change both the body and arm color, but when the current version only showed a body field I assumed that meant arm colors were tied to body colors in the current version. However, upon loading the edited save the original arm colors were still in place for any duplicant I tried to change the body color of.

**Comment by RoboPhred** [comment]
You are right, I forgot those are separate things!  I will try to make time to add support for that into the editor.

**Comment by RoboPhred** [comment]
Fixed in 3.8.4
