### ISSUE TITLE
How can I deploy local to test my translate? 

### ISSUE THREAD

**Issue by gstvinf** [RoboPhred/oni-duplicity#57]
Hello everybody.

I want to translate this project to Portuguese, but I couldn't deploy to test my translate.

I tried npm start or yarn start but didn't work.

Thanks

**Comment by RoboPhred** [comment]
The package is set up to run with `npm start`.  Make sure you install the dependencies first.

I have set up the scripts to function regardless of what operating system you have, so it should be compatible.

Are you experiencing any errors when trying to run it?
