### ISSUE TITLE
Launch Upgrade Compatibility - 7.11 (woo hoo!)

### ISSUE THREAD

**Issue by sienar1** [RoboPhred/oni-duplicity#59]
Crazy that they bumped 3 minor version numbers between the QoL3 update and the Launch Upgrade test branch. Looking forward to Duplicity supporting the new changes.

Thanks RoboPhred and other contributors!

**Comment by morinje** [comment]
How long does it usually take for them to update?

**Comment by jfmmm** [comment]
How long does it usually take for them to update?

**Comment by Lakefruit** [comment]
Bump, please update ASAP

**Comment by pittypuyo** [comment]
Thank you for your work. waiting in line.

**Comment by SueWasTaken** [comment]
Thanks for the great work. Waiting for the update!

**Comment by cmad157** [comment]
+1

**Comment by hawshemi** [comment]
**Please update to 7.11 version.**

Thanks

**Comment by RoboPhred** [comment]
I am working on updating the editor.  So far there appear to be no changes that break the parser, but there might always be differences in the game object data that break duplicity.  I am currently waiting to get a built up save file so I can test everything.  If you have a large save file with access to space, please consider sending it over for testing.

**Comment by cmad157** [comment]
> I am working on updating the editor. So far there appear to be no changes that break the parser, but there might always be differences in the game object data that break duplicity. I am currently waiting to get a built up save file so I can test everything. If you have a large save file with access to space, please consider sending it over for testing.

I've got one but it has some mods, would that be an issue?

**Comment by RoboPhred** [comment]
I got one from the Klei form thread, and tested the editor.  I couldn't find any issues with it, so hopefully whatever changes were made are not in the data the editor works on.

I released a new version with the version check updated to 7.11, so LU saves should work in the editor now.

Let me know (in a new issue) if you find any bugs with it.

**Comment by sienar1** [comment]
Thanks RoboPhred!!!!
