### ISSUE TITLE
Update 5/25 broke the editor

### ISSUE THREAD

**Issue by Abakus139** [RoboPhred/oni-duplicity#6]
I've come to love your tool, please make it compatible with the latest update. When I load an edited file, it crashes (started 1 hour ago). Never had any problems before. 
Thx for the great work so far.

**Comment by RoboPhred** [comment]
Can you reproduce this on a new, clean save?
How does the save editor act if you load an edited file back into it?  Any problems there?
If you can reproduce it with a clean save, try to send the save to me, or give me the exact changes you made.

The save editor goes out of its way to try and produce an exact copy of the original data where nothing was touched, but this only happens at the game object level.  It is possible they introduced a new field outside of that, but I would expect such a field to cause the editor to fail to load the file to begin with.

At the very least, Klei would have bumped the save version number, as older versions of ONI would have the same issue.  The editor detects that as well, and refuses to load files outside of its supported range.

**Comment by Abakus139** [comment]
On friday, nothing worked. When I started a new game, edited and saved it, the program crashed immediately upon trying to load it in ONI. I rolled back the update via console and steamdb and went on playing. Yesterday (monday 28th) I switched back to the updated version and just tried again, and now it works like before. I am happy and my issue is gone. Thanks for your time anyway.
