### ISSUE TITLE
Sandbox Mode

### ISSUE THREAD

**Issue by courtneyp13** [RoboPhred/oni-duplicity#60]
I am trying to disable sandbox mode that I enabled in game, but when i load the file here it says it is disabled. Even if I re-enable sandbox, save, disable, save, and load it. It still has sandbox mode enabled ingame.

**Comment by RoboPhred** [comment]
I have a possible solution for this, I found another save game option buried within the game data separate from the difficulty data displayed on the overview screen.  I have modified the editor so it will try to toggle this value as well when you change the main difficulty setting.

If you want to do it manually, the other sandbox setting is located at SaveGame/gameObjects/SaveGame/0/behaviors/SaveGame/templateData/sandboxEnabled
