### ISSUE TITLE
the duplicant's clones sleep in the same bed

### ISSUE THREAD

**Issue by gyur13** [RoboPhred/oni-duplicity#61]
if I clone a duplicant the clone sleep in the first duplicant's bed

**Comment by RoboPhred** [comment]
This seems to be related to duplicants being referenced by other components through MinionIdentity.assignableProxy.

The data type is a Ref, which seems to target a MinionAssignableProxy by KPrefabID.  This points back at its minion through target_instance_id, and also as an "Ownables" behavior, where I suspect the bed data is stored.

I probably need to generate a new empty MinionAssignableProxy for the clone.

**Comment by RoboPhred** [comment]
Fixed in 3.8.4
