### ISSUE TITLE
Salt water geysers don't appear in geysers menu

### ISSUE THREAD

**Issue by adammartinez271828** [RoboPhred/oni-duplicity#63]
Salt water geysers don't appear in the geysers submenu.  Nor can other geysers be changed to become salt water geysers.

Steps to reproduce:  Generate a world with a salt water geyser.  Reveal the geyser.  Save game.  Open save for editing.

![image](https://user-images.githubusercontent.com/3824752/63031254-bb10a680-be81-11e9-8030-50cc6399dee5.png)

My spit-take is that you have or are getting a list of geyser types and the new geyser isn't in there.

**Comment by RoboPhred** [comment]
You are right, this geyser list was copied from the game code in an older version, and needs to be updated.

**Comment by RoboPhred** [comment]
Fixed in 3.8.4
