### ISSUE TITLE
Issue with clones and door/suits

### ISSUE THREAD

**Issue by TearItAppart** [RoboPhred/oni-duplicity#64]
When clone is created, original dup is no longer in door menu, only clone, but both are blocked when 
use. 
Clones can not wear any suits, when passing trough atmo suit check point animations is on, suit is removed from dock but dup not wearing it and suffer from enviroment, when he returning suit, animation is on, but suit spawn at original dup location. 
Please is it possible to get original dupes into door menu along with clones at least so clone can be blocked from access to atmo suit check point?

**Comment by RoboPhred** [comment]
I think this is the same ownership issue as #61

**Comment by RoboPhred** [comment]
I think I fixed the underlying cause of this.  Please check in 3.8.4
