### ISSUE TITLE
Using Raw Editor destroys file

### ISSUE THREAD

**Issue by brau5e** [RoboPhred/oni-duplicity#65]
When I use the Raw Editor to change the temperature or the units of the oxyrock in this save file, then apply the changes and download the modified file I just get a 20 kB file that doesn't  work.

Otherwise: I love your work here!

[Star-crossed Spacecamp.zip](https://github.com/RoboPhred/oni-duplicity/files/3537150/Star-crossed.Spacecamp.zip)

**Comment by KairuByte** [comment]
I've noticed that small/new saves work fine, but anything larger than a few MB seems to cause this problem.

**Comment by RoboPhred** [comment]
Thanks for this.  I am currently reworking the raw editor, and will test it against this save before publishing it.

**Comment by RoboPhred** [comment]
I cant test this save anymore as the versions have bumped, but I believe I have figured out what was causing the issue.  A new save editor will be available in the next release, that should hopefully solve the problem.
