### ISSUE TITLE
How to revive or remove Dup from save?

### ISSUE THREAD

**Issue by GamezUzer** [RoboPhred/oni-duplicity#67]
I have one dupe died, but are show in some list. I hope know how to remove he from save? Is no have this funtion on this editor?
I try edit stammina to full or to zero and not solve, i no know where he are died or cannot found.

Edit: I forgot to say, the name of the dupe (Abe)

[save_files.zip](https://github.com/RoboPhred/oni-duplicity/files/3626393/save_files.zip)

**Comment by RoboPhred** [comment]
Death is complicated as there are many other variables that get updated to reflect the death.  It might be possible to revive a dup by clearing out their AI state, but other aspects of the game might become wonky as a result.

Deleting a dup outright might be a bit better on the game, but still runs into the problem that data for that dup is stored across multiple game objects, and deleting it might likewise have adverse effects.

At any rate, cloning a dead duplicant should "resurrect" that duplicant in that you get a new (living) dup with identical stats.
