### ISSUE TITLE
Names in Trait

### ISSUE THREAD

**Issue by GamezUzer** [RoboPhred/oni-duplicity#68]
In Editor;
In Trait Button:
Duplicants-->Select Any Dup-->ADD TRAIT

I see names as ''Ellie''... is correct? What do it? Name of a Dup as trait? Any is wrong here?

**Comment by RoboPhred** [comment]
Those are real traits, although they are not used by the game normally.  There are 3 traits named after dups that apparently were intended to apply to dups on that name.  I have heard this referred to as "congenital traits" before, and I think its a dropped feature.

At any rate, I include them in the list of all traits so people can mess about with them if they want.
