### ISSUE TITLE
Geysers issue

### ISSUE THREAD

**Issue by SwordlessLink** [RoboPhred/oni-duplicity#7]
Once a modified Geyser has been changed, it doesnt seem to follow the commands, instead it just makes them spew out Guld (solid pickupable item) and that is it

**Comment by RoboPhred** [comment]
Can you check if this is happening in the CU?

The save file does not actually have the capability to make a change that can do this.  It simply stores a name of a specific geyser type, and a random factor whose meaning gets interpreted by the game on load.

If you are able to reproduce it, please send in a before-edit and after-edit save file so I can hunt it down.
