### ISSUE TITLE
7.12 update needed

### ISSUE THREAD

**Issue by Sinesthesia** [RoboPhred/oni-duplicity#70]
Duplicity is still on 7.11

**Comment by Lymen78** [comment]
Any update on fixing this?

**Comment by FL4KS** [comment]
> Duplicity is still on 7.11

Any Chance we will get an update for 7.12

**Comment by quonic** [comment]
I think this is due to [oni-save-parser](https://github.com/RoboPhred/oni-save-parser) only supports up to [7.11](https://github.com/RoboPhred/oni-save-parser/blob/a0616808a3a87099aa41aeb82b5a33ceea723258/src/save-structure/parser.ts#L44).

**Comment by Sh1z0** [comment]
I found this editor a day after 7.12 got out... just my luck xD

**Comment by quonic** [comment]
Created and issue over in the [oni-save-parser](https://github.com/RoboPhred/oni-save-parser/issues/9) repo.

**Comment by RoboPhred** [comment]
New version is ready.  Supports save 7.12
