### ISSUE TITLE
Parser not compatible

### ISSUE THREAD

**Issue by daveysterkman** [RoboPhred/oni-duplicity#72]
Hi,

When I try to use duplictity, I get the following error message: 'Error while processing content: Save version "7.11" is not compatible with this parser. Expected version "7.12".'
Is this a known issue?
Thanks,

Davey

**Comment by RoboPhred** [comment]
The editor follows the mainline steam release for compatibility.  Compatibility against older versions is not preserved.  Make sure your game is up to date on steam.
