### ISSUE TITLE
Duplicity no longer loading save Geysers

### ISSUE THREAD

**Issue by RonivanFontanez** [RoboPhred/oni-duplicity#78]
As the title says, the app is no longer showing for me the geysers of the map, just a black screen with nothing. Such thing happened recently, because until two days ago it was working normally. Nothing have changed in my game files here nor mods, I just started a new game. I tested creating several new games, and all have the same strange issue to Geysers in Duplicity.

**Comment by RoboPhred** [comment]
When you test new games, do you reveal the geysers on the map before loading it? A good way to do that is to toggle debug mode on to reveal the entire map and let everything load in. 

 Geysers do not spawn until they are encountered.  There is placeholder data before they spawn, but the editor does not show those currently.

If you have a save file containing geysers you found in-game that do not show up on the list, I would be interested in getting a copy to test with.

**Comment by RoboPhred** [comment]
Unable to reproduce
