### ISSUE TITLE
Error while processing content: Identifier "Kelmen-MediumPowerTransformer" has invalid characters.

### ISSUE THREAD

**Issue by bryoco** [RoboPhred/oni-duplicity#82]
Failed to Load
Error loading save
Error while processing content: Identifier "Kelmen-MediumPowerTransformer" has invalid characters. This most likely indicates a parser error or change in serializer standards.

Traced to `oni-save-parser/src/utils.ts @ line 6 `

```typescript
const REGEX_IDENTIFIER
```

**Comment by bryoco** [comment]
Probably caused by mod: https://steamcommunity.com/sharedfiles/filedetails/?id=1854420483
Save file: https://drive.google.com/open?id=1kd6FcBOgZ7NFvwHKqoILilKZnxoTOmvs

**Comment by RoboPhred** [comment]
Thanks for the reproduction case, and a big thanks for the MR!  However, given that we also have #83 reporting mods using non-ascii characters its about time to remove the unsuccessful attempt at regexing a valid identifier and fall back on something much more permissive, such as a printable character and max length check.

I hope to get this in by the end of the next weekend.

**Comment by RoboPhred** [comment]
This fix should now be live.
