### ISSUE TITLE
Stuck on loading

### ISSUE THREAD

**Issue by Wacko71** [RoboPhred/oni-duplicity#85]
Hi, yesterday all was working fine but this morning when trying to  load save file it gets stuck on "loading" and will not continue. Tried offline mode as well but still no luck.

Reinstalled ONI v394616 today and started new game, new game with all my old mods, new game with mod loader and world generation editor but all 3 still get stuck on the same loading screen.

**Comment by Oddness-1** [comment]
Same problem.

**Comment by Boolyman** [comment]
Same

**Comment by SueWasTaken** [comment]
Same.

**Comment by bdelee-zz** [comment]
Same here.  We need to revert the last update.

**Comment by RoboPhred** [comment]
This was due to a misconfiguration during setup of offline mode.  It has been fixed and deployed.
