### ISSUE TITLE
Needs to be updated for game version "7.16"

### ISSUE THREAD

**Issue by bdelee-zz** [RoboPhred/oni-duplicity#86]
When loading a save file, the tool gives the comment:

`Error while processing content: Save version "7.16" is not compatible with this parser. Expected version "7.15".`

**Comment by Oddness-1** [comment]
Same.

**Comment by Romano77** [comment]
Would be nice to let us open a new version saved file without the possibility to do modification other than the "SaveMinorVersion":xx,"" flag  ;)

**Comment by RoboPhred** [comment]
Originally it allowed any minor version to go through, but back during beta there was a breaking change on a minor version that lead to data corruption, so I made it more strict.

Now that the game is more stable, I can look at letting the user override the version check, in a "here be dragons" sort of way.

**Comment by Romano77** [comment]
w00t ! Thanks for the answer  ;) 
I understand and let you feel if it's valuable in time depending the numbers of update to come.

**Comment by Marcoevich** [comment]
Maybe you want to update the readme as well :) It still mentions support until 7.15 (recreation pack).
