### ISSUE TITLE
Older Savegames

### ISSUE THREAD

**Issue by Endgegner** [RoboPhred/oni-duplicity#93]
Error while processing content: Save version "7.16" is not compatible with this parser. Expected version "7.17".

Would you mind providing previous versions of Oni-Duplicity, so we can edit older savegames too? Especially for the automation package, which is very stable on my end (Duplicity 3.15.2)

**Comment by RoboPhred** [comment]
I re-uploaded the previous version to [/legacy-7.16](https://robophred.github.io/oni-duplicity/legacy-7.16).  You can use it to edit the older saves.
