### ISSUE TITLE
Not working to My Saves

### ISSUE THREAD

**Issue by GamezUzer** [RoboPhred/oni-duplicity#94]
I make changes in savegame with this editor, save changes, load game, but game load a previuos savegame without changes and old, without errors or advise messages, only load old savegame.
:(

**Comment by RoboPhred** [comment]
When clicking "save", the website should process the file then prompt you to download the modified copy.  If your browser isn't downloading the new file, check to see if you have a popup blocker that might be getting in the way.

**Comment by GamezUzer** [comment]
I always did it the same way, it always worked until a recent game update,
now when I modify it, except for changes, this is the most recent file,
because the previous one is 'savegame - copy', the game simply ignores the
newest one, as if it was corrupted, and automatically loads the last
auto-save before the one modified by the editor.

Em sáb., 23 de mai. de 2020 às 11:36, RoboPhred <notifications@github.com>
escreveu:
